### ISSUE TITLE
The import type 'Foo' is defined multiple times

### ISSUE THREAD

**Issue by ylatuya** [praeclarum/Continuous#41]
I am experiencing the following error when I try to visualize a class:

```
2015-12-29 19:55:37.754 LongoMatch.Mobile[35844:3225971] ERROR: The imported type `LongoMatch.Drawing.Widgets.TeamTagger' is defined multiple times
```

Let me know how can I add more details to help you, because that's the only error I see in the ouput, no exception is raised or stack trace printed in the output logs.

**Comment by praeclarum** [comment]
That error is pretty descriptive - looks like you have multiple versions of the same class linked to your app. Not sure if I can work around that.

**Comment by ylatuya** [comment]
Indeed, this is a library I build in my project using a shared project and I was linking against the shared the project instead of the library in the iOS application, and therefore adding the same class twice. I am now hitting #26 but this one has a workaround. Thanks for this awesome addin!
