### ISSUE TITLE
Support for Xamarin Studio 6

### ISSUE THREAD

**Issue by rid00z** [praeclarum/Continuous#43]
The new Xamarin Inspector requires XS6 and I cannot get the addin to work with XS6. 

<img width="432" alt="screen shot 2016-03-05 at 1 57 21 pm" src="https://cloud.githubusercontent.com/assets/1546173/13545274/771d1f2a-e2da-11e5-8284-460f0a27175b.png">

**Comment by vbullinger** [comment]
Guys. This thing's dead in the water without updating these references. I mean, literally: either update your repository or delete the whole thing so people don't waste their time.

**Comment by dapullar** [comment]
@vbullinger check out rdavisau's fork. Works decently well with the NuGet package + manually building the add-in.

**Comment by praeclarum** [comment]
I just accepted the PR for this. Sorry for the delays everyone. I'm working on getting this smoothed out today.

**Comment by wes566** [comment]
Is this change in the published add-in?

I see v2.0.4 in XS add-in manager, but it fails to install in Xamarin Studio for me.  Don't see v2.0.4 release tag so not sure when it was released.

BTW, I'm using XS v6.1.2 (build 44).

**Comment by praeclarum** [comment]
Xamarin Studio keeps breaking their API and I've had to bump this puppy up to require **6.2** (currently in the Alpha channel). I'm very sorry for this.
