### ISSUE TITLE
NotSupportedException in CSharp.Evaluator.Evaluate from VM.Eval

### ISSUE THREAD

**Issue by praeclarum** [praeclarum/Continuous#46]
When building for Xamarin Studio 6, my app fails to watch a type.

It seems like Mono.CSharp is not being swapped out by the inspector anymore. I have run with Inspector and it is able to execute code dynamically, but Continuous is not able to.

@rdavisau are you seeing this error?

```
error: System.NotSupportedException: Specified method is not supported.
  at Mono.CSharp.AssemblyDefinitionDynamic.Create (System.AppDomain domain, System.Reflection.Emit.AssemblyBuilderAccess access) [0x00000] in /Users/builder/data/lanes/3985/62816dd6/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/mcs/reflection.cs:223 
  at Mono.CSharp.Evaluator.CompileBlock (Mono.CSharp.Class host, Mono.CSharp.Undo undo, Mono.CSharp.Report Report) [0x00066] in /Users/builder/data/lanes/3985/62816dd6/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/mcs/eval.cs:707 
  at Mono.CSharp.Evaluator.Compile (System.String input, Mono.CSharp.CompiledMethod& compiled) [0x000e3] in /Users/builder/data/lanes/3985/62816dd6/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/mcs/eval.cs:268 
  at Mono.CSharp.Evaluator.Evaluate (System.String input, System.Object& result, System.Boolean& result_set) [0x00006] in /Users/builder/data/lanes/3985/62816dd6/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/mcs/eval.cs:359 
  at Continuous.Server.VM.Eval (System.String code) [0x00069] in /Users/fak/Dropbox/Projects/Continuous/Continuous.Server.Core/VM.cs:37 
```

**Comment by rdavisau** [comment]
Yes - I did notice this about a week ago and realised it might be linked to updating the Inspector to 1.0 On 1.0 I was not seeing the special inspector output in the build logs that referenced swapping out dlls; after rolling back to an earlier release ([0.9.0](https://developer.xamarin.com/releases/interactive/preview/inspector-0.9.0/)), the build logs came back and Continuous works again. I had been meaning to find out whether it was just a co-incidence, but as you've experience the same I'm thinking not. I think you have the connections to make a case for re-inclusion of this behaviour \😎/

Worth noting that even though I uninstalled the 1.0 version of workbooks (by deleting the application from Applications), after reinstalling the older version things are a little out of whack. Workbooks standalone still reports it is 1.0, and trying to use the inspector icon from within Xamarin Studio to attach to the running app displays an error. Minor issues for me; I prefer to have Continuous working. - if it's going away they can pry this magic from my cold dead hands and not a moment earlier 👯.

**Comment by praeclarum** [comment]
Thanks for getting back to me so quickly! Darn, I was afraid you'd say something along these lines.

I have filed a bug against Xamarin. I'm hoping they'll suggest an easy workaround.

https://bugzilla.xamarin.com/show_bug.cgi?id=48239

**Comment by rdavisau** [comment]
Fingers crossed! Looking through the release notes I think it was actually mentioned in [0.99](https://developer.xamarin.com/releases/interactive/preview/inspector-0.99.0/) towards the bottom. Early on in XS6 before the inspector plugin had been updated to work with it, I did get Continuous working by adding a post build step that overwrote the .dlls in the app bundle manually, but that's a hack best avoided if possible.

**Comment by abock** [comment]
@praeclarum details are in my comment on the bug you filed (thank you), but I wanted to also note it here:

> As an immediate workaround to Continuous users, `--enable-repl` can be passed in the iOS project settings for "additional mtouch arguments"

<img width="1072" alt="screen shot 2016-11-30 at 5 02 24 pm" src="https://cloud.githubusercontent.com/assets/49539/20773249/e598e402-b71e-11e6-8ce6-6f08a184fe09.png">

Additionally we are providing sample code (courtesy @sandyarmstrong) for you for integrate into the Continuous addin, under the MIT license:

* https://gist.github.com/abock/9c732e6008f60b871dc2087d5d776a84

**Comment by sandyarmstrong** [comment]
@rdavisau deleting `Xamarin Workbooks.app` isn't sufficient to uninstall the Inspector. As of 1.0, you would also need to remove the following paths for a complete uninstall:

```
/Library/Frameworks/Xamarin.Interactive.framework/
~/Library/Application Support/XamarinStudio-6.0/LocalInstall/Addins/Xamarin.Interactive/
```

**Comment by praeclarum** [comment]
@abock I can confirm that it works!

https://github.com/praeclarum/Continuous/blob/master/Continuous.Client.MonoDevelop/ios-repl-swizzle.cs

Thanks again for your quick response and the detailed fix.

Just for clarification, this means this add-in is no longer dependent on Inspector?

**Comment by abock** [comment]
@praeclarum glad to hear it!

And you are correct, you will no longer hold a dependency on Inspector at all. The actual SRE enabled mscorlib and friends are shipped in Xamarin.iOS itself (and have for years - the functionality has always been available via passing `--enable-repl` to `mtouch`).

The swizzling that our Inspector addin did was a convenience so that we did not have to tell users to add the `--enable-repl` flag to their project.
